<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CoursesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('courses')->delete();
        
        \DB::table('courses')->insert(array (
            0 => 
            array (
                'id' => 2,
                'title' => 'آموزش _HTML_مقدماتی تا پیشرفته',
                'price' => 99000,
                'discount' => 120,
                'url_slug' => 'html-tutorial',
                'requirements' => 'آمادگی و اشتیاق برای یادگیری_بدون نیاز به تجربه برنامه نویسی_دانش اولیه در مورد اینترنت و ترکیب وب سایت ها توصیه می شود اما ضروری نیست.',
                'short_description' => 'آموزش HTML یک مسیر اساسی برای ورود به دنیای طراحی وب است. این دوره با مفاهیم پایه‌ای شروع شده و به شما امکان می‌دهد تا ساختار اصولی وبسایت‌های خود را با استفاده از تگ‌ها و ویژگی‌های HTML به درستی بسازید.',
                'what_you_will_learn' => 'آشنایی با تگ‌های HTML و نحوه استفاده از آنها_یادگیری ساختار کلی یک سند HTML_استفاده از تگ‌های مختلف برای عناوین، پاراگراف‌ها، تصاویر، لیست‌ها و ..._ایجاد لینک‌های داخلی و خارجی_درج تصاویر در صفحات وب_استفاده از عناصر مختلف فرم مانند دکمه‌ها، کادرهای متن و ...',
                'long_description' => NULL,
                'teacher_id' => 1,
                'category_id' => 3,
                'active' => 0,
                'created_at' => '2024-01-24 17:52:37',
                'updated_at' => '2024-02-24 12:54:41',
            ),
            1 => 
            array (
                'id' => 3,
                'title' => 'آموزش CSS از مقدماتی تا پیشرفته',
                'price' => 0,
                'discount' => 0,
                'url_slug' => NULL,
                'requirements' => 'تسلط بر HTTML',
                'short_description' => 'تسلط کامل بر  دستورات CSS_توانایی پیاده سازی و استایل دهی به صفحات وب ',
                'what_you_will_learn' => 'تسلط کامل بر  دستورات CSS_توانایی پیاده سازی و استایل دهی به صفحات وب ',
                'long_description' => NULL,
                'teacher_id' => 1,
                'category_id' => 3,
                'active' => 0,
                'created_at' => '2024-01-24 17:56:47',
                'updated_at' => '2024-01-24 18:50:08',
            ),
            2 => 
            array (
                'id' => 4,
            'title' => 'آموزش واکنشگرایی (Responsive layout) قالب وب سایت',
                'price' => 0,
                'discount' => 0,
                'url_slug' => NULL,
                'requirements' => 'تسلط بر HTTML_تسلط بر CSS',
                'short_description' => 'تسلط بر قوانین واکنشگرایی قالب وبسایت_توانایی ریسپانسیو سازی قالب های وب سایت',
                'what_you_will_learn' => 'تسلط بر قوانین واکنشگرایی قالب وبسایت_توانایی ریسپانسیو سازی قالب های وب سایت',
                'long_description' => NULL,
                'teacher_id' => 1,
                'category_id' => 3,
                'active' => 0,
                'created_at' => '2024-01-24 18:06:07',
                'updated_at' => '2024-01-24 18:06:07',
            ),
            3 => 
            array (
                'id' => 5,
                'title' => 'پروژه تسلط بر  HTML & CSS | طراحی قالب دیجی کالا',
                'price' => 0,
                'discount' => 0,
                'url_slug' => NULL,
                'requirements' => 'تسلط بر HTTML_تسلط بر CSS_تسلط بر مفاهیم واکنشگرایی و ریسپانسیو سازی قالب وبسایت',
                'short_description' => 'توانایی حل مسئله_تسلط بر دستورات HTML_تسلط بر دستورات CSS_توانایی کدزنی و طراحی انواع قالب های ریسپانسیو وب سایت در حد پیشرفته',
                'what_you_will_learn' => 'توانایی حل مسئله_تسلط بر دستورات HTML_تسلط بر دستورات CSS_توانایی کدزنی و طراحی انواع قالب های ریسپانسیو وب سایت در حد پیشرفته',
                'long_description' => NULL,
                'teacher_id' => 1,
                'category_id' => 3,
                'active' => 0,
                'created_at' => '2024-01-24 18:11:02',
                'updated_at' => '2024-01-24 22:00:32',
            ),
            4 => 
            array (
                'id' => 6,
                'title' => 'آموزش PHP از مقدماتی تا پیشرفته',
                'price' => 0,
                'discount' => 0,
                'url_slug' => NULL,
                'requirements' => 'آشنایی با HTML_آشنایی با CSS',
                'short_description' => 'تسلط بر مفاهیم و سینتکس زبان برنامه نویسی PHP',
                'what_you_will_learn' => 'تسلط بر مفاهیم و سینتکس زبان برنامه نویسی PHP',
                'long_description' => NULL,
                'teacher_id' => 1,
                'category_id' => 4,
                'active' => 0,
                'created_at' => '2024-01-24 18:17:09',
                'updated_at' => '2024-01-24 18:50:16',
            ),
            5 => 
            array (
                'id' => 7,
                'title' => 'آموزش دیتابیس MYSQL',
                'price' => 0,
                'discount' => 0,
                'url_slug' => NULL,
                'requirements' => 'تسلط بر PHP',
                'short_description' => 'توانایی ایجاد دیتابیس ',
                'what_you_will_learn' => 'توانایی ایجاد دیتابیس ',
                'long_description' => NULL,
                'teacher_id' => 1,
                'category_id' => 4,
                'active' => 0,
                'created_at' => '2024-01-24 18:21:11',
                'updated_at' => '2024-01-24 18:21:11',
            ),
            6 => 
            array (
                'id' => 8,
                'title' => 'پروژه های تسلط بر PHP,MYSQL ',
                'price' => 0,
                'discount' => 0,
                'url_slug' => NULL,
                'requirements' => 'آشنایی با HTML_آشنایی با CSS_آشنایی با زبان PHP_آشنایی با دیتابیس MYSQL',
                'short_description' => 'توانایی حل مسئله_تسلط بر دستورات PHP, SQL',
                'what_you_will_learn' => 'توانایی حل مسئله_تسلط بر دستورات PHP, SQL',
                'long_description' => NULL,
                'teacher_id' => 1,
                'category_id' => 4,
                'active' => 0,
                'created_at' => '2024-01-24 18:29:49',
                'updated_at' => '2024-01-24 22:27:43',
            ),
            7 => 
            array (
                'id' => 9,
            'title' => 'آموزش فریمورک لاراول( Laravel ) مقدماتی تا پیشرفته',
                'price' => 0,
                'discount' => 0,
                'url_slug' => NULL,
                'requirements' => 'آشنایی با HTML_آشنایی با CSS_تسلط بر PHP_تسلط بر MYSQL',
                'short_description' => 'آشنایی با HTML_آشنایی با CSS_تسلط بر PHP_تسلط بر MYSQL',
                'what_you_will_learn' => 'آشنایی با HTML_آشنایی با CSS_تسلط بر PHP_تسلط بر MYSQL',
                'long_description' => NULL,
                'teacher_id' => 1,
                'category_id' => 4,
                'active' => 0,
                'created_at' => '2024-01-24 18:32:18',
                'updated_at' => '2024-01-24 18:50:22',
            ),
            8 => 
            array (
                'id' => 10,
            'title' => 'پروژه برنامه نویسی بلاگ برای تسلط بر فریمورک لاراول ( Laravel )',
                'price' => 0,
                'discount' => 0,
                'url_slug' => NULL,
            'requirements' => 'آشنایی با HTML_آشنایی با CSS_تسلط بر PHP_تسلط بر MYSQL_تسلط بر فریمورک لاراول(Laravel)',
            'short_description' => 'آشنایی با HTML_آشنایی با CSS_تسلط بر PHP_تسلط بر MYSQL_تسلط بر فریمورک لاراول(Laravel)',
            'what_you_will_learn' => 'آشنایی با HTML_آشنایی با CSS_تسلط بر PHP_تسلط بر MYSQL_تسلط بر فریمورک لاراول(Laravel)',
                'long_description' => NULL,
                'teacher_id' => 1,
                'category_id' => 4,
                'active' => 0,
                'created_at' => '2024-01-24 18:39:47',
                'updated_at' => '2024-01-24 22:24:30',
            ),
            9 => 
            array (
                'id' => 11,
            'title' => 'آموزش بوت استرپ 5 (Bootstrap)',
                'price' => 0,
                'discount' => 0,
                'url_slug' => NULL,
                'requirements' => 'تسلط بر HTTML_تسلط بر CSS_تسلط بر مفاهیم واکنشگرایی و ریسپانسیو سازی قالب وبسایت',
                'short_description' => 'تسلط بر HTTML_تسلط بر CSS_تسلط بر مفاهیم واکنشگرایی و ریسپانسیو سازی قالب وبسایت',
                'what_you_will_learn' => 'تسلط بر HTTML_تسلط بر CSS_تسلط بر مفاهیم واکنشگرایی و ریسپانسیو سازی قالب وبسایت',
                'long_description' => NULL,
                'teacher_id' => 1,
                'category_id' => 3,
                'active' => 0,
                'created_at' => '2024-01-24 18:48:36',
                'updated_at' => '2024-01-24 18:48:36',
            ),
            10 => 
            array (
                'id' => 12,
            'title' => 'آموزش جاوا اسکریپت (JavaScript) مقدماتی تا پیشرفته',
                'price' => 0,
                'discount' => 0,
                'url_slug' => NULL,
                'requirements' => 'تسلط بر HTTML_تسلط بر CSS',
                'short_description' => 'تسلط بر HTTML_تسلط بر CSS',
                'what_you_will_learn' => 'تسلط بر HTTML_تسلط بر CSS',
                'long_description' => NULL,
                'teacher_id' => 1,
                'category_id' => 3,
                'active' => 0,
                'created_at' => '2024-01-24 18:50:56',
                'updated_at' => '2024-01-24 18:50:56',
            ),
            11 => 
            array (
                'id' => 13,
            'title' => 'مینی پروژه های تسلط بر جاوا اسکریپت ( JavaScript )',
                'price' => 0,
                'discount' => 0,
                'url_slug' => NULL,
            'requirements' => 'تسلط بر HTTML_تسلط بر CSS_تسلط بر جاوا اسکریپت ( JavaScript )',
            'short_description' => 'تسلط بر HTTML_تسلط بر CSS_تسلط بر جاوا اسکریپت (JavaScript)',
            'what_you_will_learn' => 'تسلط بر HTTML_تسلط بر CSS_تسلط بر جاوا اسکریپت (JavaScript)',
                'long_description' => NULL,
                'teacher_id' => 1,
                'category_id' => 3,
                'active' => 0,
                'created_at' => '2024-01-24 18:51:42',
                'updated_at' => '2024-01-24 22:24:23',
            ),
            12 => 
            array (
                'id' => 14,
            'title' => 'آموزش فریمورک لایووایر ( Livewwire ) مقدماتی تا پیشرفته',
                'price' => 0,
                'discount' => 0,
                'url_slug' => NULL,
            'requirements' => 'آشنایی با HTML_آشنایی با CSS_تسلط بر PHP_تسلط بر MYSQL_تسلط بر فریمورک لاراول(Laravel)',
            'short_description' => 'آشنایی با HTML_آشنایی با CSS_تسلط بر PHP_تسلط بر MYSQL_تسلط بر فریمورک لاراول(Laravel)',
            'what_you_will_learn' => 'آشنایی با HTML_آشنایی با CSS_تسلط بر PHP_تسلط بر MYSQL_تسلط بر فریمورک لاراول(Laravel)',
                'long_description' => NULL,
                'teacher_id' => 1,
                'category_id' => 4,
                'active' => 0,
                'created_at' => '2024-01-24 21:58:30',
                'updated_at' => '2024-01-24 21:58:30',
            ),
            13 => 
            array (
                'id' => 15,
                'title' => 'پروژه تسلط بر  Laravel & Livewire | پنل مدیریت دیجی کالا',
                'price' => 0,
                'discount' => 0,
                'url_slug' => NULL,
            'requirements' => 'آشنایی با HTML_آشنایی با CSS_تسلط بر PHP_تسلط بر MYSQL_تسلط بر فریمورک لاراول(Laravel)_تسلط بر فریمورک لایووایر(Livewire)',
            'short_description' => 'آشنایی با HTML_آشنایی با CSS_تسلط بر PHP_تسلط بر MYSQL_تسلط بر فریمورک لاراول(Laravel)_تسلط بر فریمورک لایووایر(Livewire)',
            'what_you_will_learn' => 'آشنایی با HTML_آشنایی با CSS_تسلط بر PHP_تسلط بر MYSQL_تسلط بر فریمورک لاراول(Laravel)_تسلط بر فریمورک لایووایر(Livewire)',
                'long_description' => NULL,
                'teacher_id' => 1,
                'category_id' => 4,
                'active' => 0,
                'created_at' => '2024-01-24 22:02:24',
                'updated_at' => '2024-01-24 22:27:14',
            ),
            14 => 
            array (
                'id' => 17,
            'title' => 'آموزش ساخت وب سرویس با لاراول ( LARAVEL REST API )',
                'price' => 0,
                'discount' => 0,
                'url_slug' => NULL,
            'requirements' => 'آشنایی با HTML_آشنایی با CSS_تسلط بر PHP_تسلط بر MYSQL_تسلط بر فریمورک لاراول(Laravel)_آشنایی با نرم افزار postman',
            'short_description' => 'آشنایی با HTML_آشنایی با CSS_تسلط بر PHP_تسلط بر MYSQL_تسلط بر فریمورک لاراول(Laravel)_آشنایی با نرم افزار postman',
            'what_you_will_learn' => 'آشنایی با HTML_آشنایی با CSS_تسلط بر PHP_تسلط بر MYSQL_تسلط بر فریمورک لاراول(Laravel)_آشنایی با نرم افزار postman',
                'long_description' => NULL,
                'teacher_id' => 1,
                'category_id' => 4,
                'active' => 0,
                'created_at' => '2024-01-24 22:23:19',
                'updated_at' => '2024-01-24 22:23:19',
            ),
            15 => 
            array (
                'id' => 18,
                'title' => 'پروژه تسلط بر بک اند | سایت دیجی کالا با Vuejs & Laravel',
                'price' => 0,
                'discount' => 0,
                'url_slug' => NULL,
            'requirements' => 'آشناآشنایی با HTML_آشنایی با CSS_تسلط بر PHP_تسلط بر MYSQL_تسلط بر فریمورک لاراول(Laravel)_آشنایی با نرم افزار postman',
            'short_description' => 'آشناآشنایی با HTML_آشنایی با CSS_تسلط بر PHP_تسلط بر MYSQL_تسلط بر فریمورک لاراول(Laravel)_آشنایی با نرم افزار postman',
            'what_you_will_learn' => 'آشناآشنایی با HTML_آشنایی با CSS_تسلط بر PHP_تسلط بر MYSQL_تسلط بر فریمورک لاراول(Laravel)_آشنایی با نرم افزار postman',
                'long_description' => NULL,
                'teacher_id' => 1,
                'category_id' => 4,
                'active' => 0,
                'created_at' => '2024-01-24 22:56:48',
                'updated_at' => '2024-01-24 22:57:03',
            ),
            16 => 
            array (
                'id' => 19,
                'title' => 'آموزش نرم افزار phpStorm',
                'price' => 0,
                'discount' => 0,
                'url_slug' => NULL,
                'requirements' => 'آشنایی با مبانی کامپیوتر',
                'short_description' => 'آشنایی با مبانی کامپیوتر',
                'what_you_will_learn' => 'آشنایی با مبانی کامپیوتر',
                'long_description' => NULL,
                'teacher_id' => 1,
                'category_id' => 6,
                'active' => 0,
                'created_at' => '2024-01-25 13:04:30',
                'updated_at' => '2024-01-25 13:04:30',
            ),
            17 => 
            array (
                'id' => 20,
                'title' => 'آموزش نرم افزار psotman',
                'price' => 0,
                'discount' => 0,
                'url_slug' => NULL,
                'requirements' => 'آشنایی با مبانی API',
                'short_description' => 'آشنایی با مبانی API',
                'what_you_will_learn' => 'آشنایی با مبانی API',
                'long_description' => NULL,
                'teacher_id' => 1,
                'category_id' => 6,
                'active' => 0,
                'created_at' => '2024-01-25 13:06:07',
                'updated_at' => '2024-01-25 13:06:07',
            ),
            18 => 
            array (
                'id' => 21,
                'title' => 'آموزش MySQL Workbench',
                'price' => 0,
                'discount' => 0,
                'url_slug' => NULL,
            'requirements' => 'آشنایی با مبانی پایگاه داده ( دیتابیس )',
            'short_description' => 'آشنایی با مبانی پایگاه داده ( دیتابیس )',
            'what_you_will_learn' => 'آشنایی با مبانی پایگاه داده ( دیتابیس )',
                'long_description' => NULL,
                'teacher_id' => 1,
                'category_id' => 6,
                'active' => 0,
                'created_at' => '2024-01-25 13:07:42',
                'updated_at' => '2024-01-25 13:07:42',
            ),
            19 => 
            array (
                'id' => 22,
                'title' => 'آموزش JQUERY',
                'price' => 0,
                'discount' => 0,
                'url_slug' => NULL,
                'requirements' => 'تسلط بر HTML_تسلط بر CSS',
                'short_description' => 'تسلط بر HTML_تسلط بر CSS',
                'what_you_will_learn' => 'تسلط بر HTML_تسلط بر CSS',
                'long_description' => NULL,
                'teacher_id' => 1,
                'category_id' => 3,
                'active' => 0,
                'created_at' => '2024-01-27 22:21:05',
                'updated_at' => '2024-01-27 22:21:05',
            ),
        ));
        
        
    }
}