<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CourseSectionLecturesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('course_section_lectures')->delete();
        
        \DB::table('course_section_lectures')->insert(array (
            0 => 
            array (
                'id' => 1,
                'title' => 'نحوه استفاده از جاوا اسکریپت | Internal -Inline - External ',
                'course_section_id' => 16,
                'course_id' => 12,
                'duration' => 663,
                'free' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-08 10:16:35',
                'updated_at' => '2024-04-08 10:19:10',
            ),
            1 => 
            array (
                'id' => 2,
                'title' => 'توابع کمکی - Helper Methods',
                'course_section_id' => 16,
                'course_id' => 12,
                'duration' => 449,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-08 10:21:19',
                'updated_at' => '2024-04-08 10:21:19',
            ),
            2 => 
            array (
                'id' => 3,
                'title' => 'متغیرها - Variables - قسمت 1',
                'course_section_id' => 16,
                'course_id' => 12,
                'duration' => 454,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-08 10:28:31',
                'updated_at' => '2024-04-08 21:00:07',
            ),
            3 => 
            array (
                'id' => 4,
                'title' => 'متغیرها - Variables - قسمت 2	',
                'course_section_id' => 16,
                'course_id' => 12,
                'duration' => 316,
                'free' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-08 10:37:30',
                'updated_at' => '2024-04-08 21:00:23',
            ),
            4 => 
            array (
                'id' => 5,
                'title' => 'قواعد نام گذاری',
                'course_section_id' => 16,
                'course_id' => 12,
                'duration' => 403,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-08 10:39:16',
                'updated_at' => '2024-04-08 10:39:17',
            ),
            5 => 
            array (
                'id' => 6,
                'title' => 'تفاوت const, let, var - قسمت 1',
                'course_section_id' => 16,
                'course_id' => 12,
                'duration' => 372,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-08 10:47:40',
                'updated_at' => '2024-04-08 10:47:41',
            ),
            6 => 
            array (
                'id' => 7,
                'title' => 'تفاوت const, let, var - قسمت 2',
                'course_section_id' => 16,
                'course_id' => 12,
                'duration' => 300,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-08 10:48:27',
                'updated_at' => '2024-04-08 10:48:28',
            ),
            7 => 
            array (
                'id' => 8,
                'title' => 'ترکیب رشته ها - String Concatenation',
                'course_section_id' => 16,
                'course_id' => 12,
                'duration' => 430,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-08 10:54:17',
                'updated_at' => '2024-04-08 10:54:17',
            ),
            8 => 
            array (
                'id' => 9,
                'title' => 'اعداد - Numbers - قسمت 1',
                'course_section_id' => 16,
                'course_id' => 12,
                'duration' => 436,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-08 10:54:47',
                'updated_at' => '2024-04-08 10:58:55',
            ),
            9 => 
            array (
                'id' => 10,
                'title' => 'اعداد - Numbers - قسمت 2',
                'course_section_id' => 16,
                'course_id' => 12,
                'duration' => 525,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-08 10:58:44',
                'updated_at' => '2024-04-08 10:58:46',
            ),
            10 => 
            array (
                'id' => 11,
                'title' => 'بررسی مفهوم - Implicit Type Conversion',
                'course_section_id' => 16,
                'course_id' => 12,
                'duration' => 887,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-08 11:12:10',
                'updated_at' => '2024-04-08 11:42:16',
            ),
            11 => 
            array (
                'id' => 12,
                'title' => 'انواع داده - Data Types',
                'course_section_id' => 16,
                'course_id' => 12,
                'duration' => 289,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-08 15:04:02',
                'updated_at' => '2024-04-08 15:04:03',
            ),
            12 => 
            array (
                'id' => 13,
                'title' => 'آرایه ها - Arrays',
                'course_section_id' => 16,
                'course_id' => 12,
                'duration' => 492,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-08 15:05:37',
                'updated_at' => '2024-04-08 15:05:38',
            ),
            13 => 
            array (
                'id' => 14,
                'title' => 'توابع - Functions - Declare, Invoke',
                'course_section_id' => 16,
                'course_id' => 12,
                'duration' => 277,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-08 15:06:33',
                'updated_at' => '2024-04-08 15:06:34',
            ),
            14 => 
            array (
                'id' => 15,
                'title' => 'توابع - Functions - Parameters, Arguments',
                'course_section_id' => 16,
                'course_id' => 12,
                'duration' => 653,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-08 15:08:31',
                'updated_at' => '2024-04-08 15:08:32',
            ),
            15 => 
            array (
                'id' => 16,
                'title' => 'توایع - Functions - Return',
                'course_section_id' => 16,
                'course_id' => 12,
                'duration' => 733,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-08 15:10:25',
                'updated_at' => '2024-04-08 15:10:27',
            ),
            16 => 
            array (
                'id' => 17,
                'title' => 'آبجکت ها - Objects',
                'course_section_id' => 16,
                'course_id' => 12,
                'duration' => 529,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-08 15:11:29',
                'updated_at' => '2024-04-08 15:11:43',
            ),
            17 => 
            array (
                'id' => 18,
                'title' => 'عبارت های شرطی -  Conditional Statements',
                'course_section_id' => 16,
                'course_id' => 12,
                'duration' => 863,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-08 15:14:39',
                'updated_at' => '2024-04-08 15:14:40',
            ),
            18 => 
            array (
                'id' => 19,
                'title' => 'عملگرهای منطقی - Logical Operators',
                'course_section_id' => 16,
                'course_id' => 12,
                'duration' => 278,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-08 15:16:17',
                'updated_at' => '2024-04-08 15:16:17',
            ),
            19 => 
            array (
                'id' => 20,
                'title' => 'سوییچ -Switch Statement',
                'course_section_id' => 16,
                'course_id' => 12,
                'duration' => 317,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-08 15:18:43',
                'updated_at' => '2024-04-08 15:18:44',
            ),
            20 => 
            array (
                'id' => 21,
                'title' => 'حلقه ها - while Loops',
                'course_section_id' => 16,
                'course_id' => 12,
                'duration' => 318,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-08 15:24:32',
                'updated_at' => '2024-04-08 15:24:32',
            ),
            21 => 
            array (
                'id' => 22,
                'title' => 'حلقه ها - Do while Loop',
                'course_section_id' => 16,
                'course_id' => 12,
                'duration' => 160,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-08 15:26:46',
                'updated_at' => '2024-04-08 15:26:47',
            ),
            22 => 
            array (
                'id' => 23,
                'title' => 'حلقه ها - For Loop	',
                'course_section_id' => 16,
                'course_id' => 12,
                'duration' => 261,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-08 15:27:56',
                'updated_at' => '2024-04-08 15:27:57',
            ),
            23 => 
            array (
                'id' => 24,
                'title' => 'متد های کار با رشته ها - String Properties and Methods',
                'course_section_id' => 17,
                'course_id' => 12,
                'duration' => 936,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-08 15:55:26',
                'updated_at' => '2024-04-08 15:55:27',
            ),
            24 => 
            array (
                'id' => 25,
                'title' => 'بررسی مفهوم Template Literals',
                'course_section_id' => 17,
                'course_id' => 12,
                'duration' => 308,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-08 15:57:32',
                'updated_at' => '2024-04-08 15:57:32',
            ),
            25 => 
            array (
                'id' => 26,
                'title' => 'متد های کار با آرایه ها - Array Properties and Methods',
                'course_section_id' => 17,
                'course_id' => 12,
                'duration' => 450,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-08 16:01:55',
                'updated_at' => '2024-04-08 16:01:56',
            ),
            26 => 
            array (
                'id' => 27,
                'title' => 'تمرین - Average Calculate',
                'course_section_id' => 17,
                'course_id' => 12,
                'duration' => 819,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-08 16:04:31',
                'updated_at' => '2024-04-08 16:04:32',
            ),
            27 => 
            array (
                'id' => 28,
                'title' => 'تفاوت Value vs Reference',
                'course_section_id' => 17,
                'course_id' => 12,
                'duration' => 466,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-08 16:07:17',
                'updated_at' => '2024-04-08 16:07:19',
            ),
            28 => 
            array (
                'id' => 29,
                'title' => 'تفاوت Null and Undefined',
                'course_section_id' => 17,
                'course_id' => 12,
                'duration' => 180,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-08 16:10:27',
                'updated_at' => '2024-04-08 16:10:28',
            ),
            29 => 
            array (
                'id' => 30,
                'title' => 'ساده‌سازی دستورات شرطی با به‌کارگیری مفهوم Ternary Operator',
                'course_section_id' => 17,
                'course_id' => 12,
                'duration' => 396,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-08 16:15:01',
                'updated_at' => '2024-04-08 16:15:02',
            ),
            30 => 
            array (
                'id' => 31,
                'title' => 'تفاوت Global Scope vs Local Scope',
                'course_section_id' => 17,
                'course_id' => 12,
                'duration' => 391,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-09 07:40:28',
                'updated_at' => '2024-04-09 07:40:29',
            ),
            31 => 
            array (
                'id' => 32,
                'title' => 'بررسی  Callback Functions در حلقه  Foreach',
                'course_section_id' => 17,
                'course_id' => 12,
                'duration' => 383,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-09 07:43:48',
                'updated_at' => '2024-04-09 07:43:49',
            ),
            32 => 
            array (
                'id' => 33,
                'title' => 'متد Filter',
                'course_section_id' => 17,
                'course_id' => 12,
                'duration' => 263,
                'free' => 0,
                'deleted_at' => '2024-04-09 07:46:20',
                'created_at' => '2024-04-09 07:44:59',
                'updated_at' => '2024-04-09 07:46:20',
            ),
            33 => 
            array (
                'id' => 34,
                'title' => 'متد Filter',
                'course_section_id' => 17,
                'course_id' => 12,
                'duration' => 263,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-09 07:53:37',
                'updated_at' => '2024-04-09 07:53:38',
            ),
            34 => 
            array (
                'id' => 35,
                'title' => 'متد Find',
                'course_section_id' => 17,
                'course_id' => 12,
                'duration' => 257,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-09 07:54:18',
                'updated_at' => '2024-04-09 07:54:19',
            ),
            35 => 
            array (
                'id' => 36,
                'title' => 'متد Map',
                'course_section_id' => 17,
                'course_id' => 12,
                'duration' => 390,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-09 07:55:40',
                'updated_at' => '2024-04-09 07:55:41',
            ),
            36 => 
            array (
                'id' => 37,
                'title' => 'بررسی Math Object',
                'course_section_id' => 17,
                'course_id' => 12,
                'duration' => 562,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-09 07:57:13',
                'updated_at' => '2024-04-09 07:57:14',
            ),
            37 => 
            array (
                'id' => 38,
                'title' => 'تابع Date قسمت 1',
                'course_section_id' => 17,
                'course_id' => 12,
                'duration' => 675,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-09 07:59:32',
                'updated_at' => '2024-04-09 07:59:33',
            ),
            38 => 
            array (
                'id' => 39,
                'title' => 'تابع Date قسمت 2 | تقویم فارسی',
                'course_section_id' => 17,
                'course_id' => 12,
                'duration' => 339,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-09 08:01:41',
                'updated_at' => '2024-04-09 08:02:52',
            ),
            39 => 
            array (
                'id' => 40,
                'title' => 'مفهوم DOM',
                'course_section_id' => 18,
                'course_id' => 12,
                'duration' => 381,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-09 08:16:26',
                'updated_at' => '2024-04-09 08:16:27',
            ),
            40 => 
            array (
                'id' => 41,
                'title' => 'متد getElementById در DOM',
                'course_section_id' => 18,
                'course_id' => 12,
                'duration' => 531,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-09 08:18:22',
                'updated_at' => '2024-04-09 08:18:23',
            ),
            41 => 
            array (
                'id' => 42,
                'title' => ' متد getElementsByTagName در DOM',
                'course_section_id' => 18,
                'course_id' => 12,
                'duration' => 591,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-09 08:20:12',
                'updated_at' => '2024-04-09 08:20:13',
            ),
            42 => 
            array (
                'id' => 43,
                'title' => 'متد getElementsByClassName در DOM',
                'course_section_id' => 18,
                'course_id' => 12,
                'duration' => 197,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-09 08:21:43',
                'updated_at' => '2024-04-09 08:21:44',
            ),
            43 => 
            array (
                'id' => 44,
                'title' => 'HTML چیست؟',
                'course_section_id' => 205,
                'course_id' => 24,
                'duration' => 152,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-09 08:58:02',
                'updated_at' => '2024-04-09 08:58:03',
            ),
            44 => 
            array (
                'id' => 45,
                'title' => 'تفاوت HTML , CSS',
                'course_section_id' => 205,
                'course_id' => 24,
                'duration' => 320,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-09 09:01:31',
                'updated_at' => '2024-04-09 09:01:32',
            ),
            45 => 
            array (
                'id' => 46,
                'title' => 'نصب و کرک PhpStorm',
                'course_section_id' => 205,
                'course_id' => 24,
                'duration' => 626,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-09 09:06:27',
                'updated_at' => '2024-04-09 09:06:27',
            ),
            46 => 
            array (
                'id' => 47,
                'title' => 'بررسی تنظمیات PhpStorm',
                'course_section_id' => 205,
                'course_id' => 24,
                'duration' => 187,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-09 09:11:34',
                'updated_at' => '2024-04-09 09:11:35',
            ),
            47 => 
            array (
                'id' => 48,
                'title' => 'مفهوم سینتکس - syntax',
                'course_section_id' => 205,
                'course_id' => 24,
                'duration' => 361,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-09 09:13:38',
                'updated_at' => '2024-04-09 09:13:39',
            ),
            48 => 
            array (
                'id' => 49,
                'title' => 'ایجاد اولین پروژه',
                'course_section_id' => 205,
                'course_id' => 24,
                'duration' => 812,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-09 09:16:13',
                'updated_at' => '2024-04-09 09:16:14',
            ),
            49 => 
            array (
                'id' => 50,
                'title' => 'متاتگ های مهم',
                'course_section_id' => 205,
                'course_id' => 24,
                'duration' => 669,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-09 09:20:01',
                'updated_at' => '2024-04-09 09:20:02',
            ),
            50 => 
            array (
                'id' => 51,
                'title' => 'بررسی تگ های Headings, Paragraphs & Typography',
                'course_section_id' => 205,
                'course_id' => 24,
                'duration' => 441,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-09 09:30:33',
                'updated_at' => '2024-04-09 09:30:34',
            ),
            51 => 
            array (
                'id' => 52,
                'title' => 'بررسی تگ های Links, Images & Attributes',
                'course_section_id' => 205,
                'course_id' => 24,
                'duration' => 841,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-09 10:18:10',
                'updated_at' => '2024-04-09 10:18:11',
            ),
            52 => 
            array (
                'id' => 53,
                'title' => 'بررسی تگ های Lists & Tables',
                'course_section_id' => 205,
                'course_id' => 24,
                'duration' => 768,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-09 10:31:00',
                'updated_at' => '2024-04-09 10:31:01',
            ),
            53 => 
            array (
                'id' => 54,
                'title' => 'بررسی تگ های Block & Inline Level Elements',
                'course_section_id' => 205,
                'course_id' => 24,
                'duration' => 535,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-09 10:33:55',
                'updated_at' => '2024-04-09 10:33:56',
            ),
            54 => 
            array (
                'id' => 55,
                'title' => 'بررسی Divs & Spans, Classes & Ids',
                'course_section_id' => 205,
                'course_id' => 24,
                'duration' => 542,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-09 10:36:25',
                'updated_at' => '2024-04-09 10:36:26',
            ),
            55 => 
            array (
                'id' => 56,
                'title' => 'کار با فرم ها - form , input, select , ...',
                'course_section_id' => 205,
                'course_id' => 24,
                'duration' => 1343,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-09 10:40:04',
                'updated_at' => '2024-04-09 10:40:05',
            ),
            56 => 
            array (
                'id' => 57,
                'title' => 'بررسی  HTML5 Semantics Tags',
                'course_section_id' => 205,
                'course_id' => 24,
                'duration' => 504,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-09 10:42:32',
                'updated_at' => '2024-04-09 10:42:32',
            ),
            57 => 
            array (
                'id' => 58,
                'title' => 'نصب بوت استرپ',
                'course_section_id' => 208,
                'course_id' => 25,
                'duration' => 532,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-09 13:17:10',
                'updated_at' => '2024-04-09 13:17:11',
            ),
            58 => 
            array (
                'id' => 59,
                'title' => 'Typography - 1',
                'course_section_id' => 208,
                'course_id' => 25,
                'duration' => 700,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-09 13:31:09',
                'updated_at' => '2024-04-09 15:12:52',
            ),
            59 => 
            array (
                'id' => 60,
                'title' => 'ادامه Typography - 1	',
                'course_section_id' => 208,
                'course_id' => 25,
                'duration' => 181,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-09 16:20:44',
                'updated_at' => '2024-04-09 16:20:45',
            ),
            60 => 
            array (
                'id' => 61,
                'title' => 'Typography - 2',
                'course_section_id' => 208,
                'course_id' => 25,
                'duration' => 470,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 08:21:24',
                'updated_at' => '2024-04-10 08:21:25',
            ),
            61 => 
            array (
                'id' => 62,
                'title' => 'رنگ ها - Colors',
                'course_section_id' => 208,
                'course_id' => 25,
                'duration' => 523,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 08:26:59',
                'updated_at' => '2024-04-10 08:27:00',
            ),
            62 => 
            array (
                'id' => 63,
                'title' => 'Borders',
                'course_section_id' => 208,
                'course_id' => 25,
                'duration' => 897,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 08:29:26',
                'updated_at' => '2024-04-10 08:29:28',
            ),
            63 => 
            array (
                'id' => 64,
                'title' => 'Display',
                'course_section_id' => 208,
                'course_id' => 25,
                'duration' => 301,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 08:30:54',
                'updated_at' => '2024-04-10 08:30:55',
            ),
            64 => 
            array (
                'id' => 65,
                'title' => 'Bootstrap Flexbox',
                'course_section_id' => 208,
                'course_id' => 25,
                'duration' => 655,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 08:32:54',
                'updated_at' => '2024-04-10 08:32:55',
            ),
            65 => 
            array (
                'id' => 66,
                'title' => 'Box Shadows',
                'course_section_id' => 208,
                'course_id' => 25,
                'duration' => 140,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 08:34:12',
                'updated_at' => '2024-04-10 08:34:12',
            ),
            66 => 
            array (
                'id' => 67,
                'title' => 'Positions',
                'course_section_id' => 208,
                'course_id' => 25,
                'duration' => 358,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 08:35:55',
                'updated_at' => '2024-04-10 08:35:56',
            ),
            67 => 
            array (
                'id' => 68,
                'title' => 'Sizing',
                'course_section_id' => 208,
                'course_id' => 25,
                'duration' => 576,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 08:37:44',
                'updated_at' => '2024-04-10 08:37:45',
            ),
            68 => 
            array (
                'id' => 69,
                'title' => 'Spacing',
                'course_section_id' => 208,
                'course_id' => 25,
                'duration' => 572,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 08:41:02',
                'updated_at' => '2024-04-10 08:41:03',
            ),
            69 => 
            array (
                'id' => 70,
                'title' => 'Containers',
                'course_section_id' => 209,
                'course_id' => 25,
                'duration' => 828,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 08:44:43',
                'updated_at' => '2024-04-10 08:44:44',
            ),
            70 => 
            array (
                'id' => 71,
                'title' => 'تفاوت HTML با CSS',
                'course_section_id' => 213,
                'course_id' => 26,
                'duration' => 178,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 09:01:11',
                'updated_at' => '2024-04-10 09:01:12',
            ),
            71 => 
            array (
                'id' => 72,
                'title' => 'نحوه اضافه کردن فایل Css به پروژه',
                'course_section_id' => 213,
                'course_id' => 26,
                'duration' => 931,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 09:16:26',
                'updated_at' => '2024-04-10 09:16:27',
            ),
            72 => 
            array (
                'id' => 73,
                'title' => 'سلکتورها در CSS',
                'course_section_id' => 213,
                'course_id' => 26,
                'duration' => 1011,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 09:20:14',
                'updated_at' => '2024-04-10 09:20:15',
            ),
            73 => 
            array (
                'id' => 74,
            'title' => 'آموزش کار DevTools  (فایرباگ) گوگل کروم',
                'course_section_id' => 213,
                'course_id' => 26,
                'duration' => 403,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 09:28:16',
                'updated_at' => '2024-04-10 09:28:17',
            ),
            74 => 
            array (
                'id' => 75,
                'title' => 'آشنایی با Color Types',
                'course_section_id' => 213,
                'course_id' => 26,
                'duration' => 534,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 09:33:46',
                'updated_at' => '2024-04-10 09:50:49',
            ),
            75 => 
            array (
                'id' => 76,
                'title' => 'آشنایی با Margin , Padding',
                'course_section_id' => 213,
                'course_id' => 26,
                'duration' => 1050,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 09:37:45',
                'updated_at' => '2024-04-10 09:37:46',
            ),
            76 => 
            array (
                'id' => 77,
                'title' => 'آشنایی با فونت ها در CSS',
                'course_section_id' => 213,
                'course_id' => 26,
                'duration' => 633,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 09:40:23',
                'updated_at' => '2024-04-10 09:40:24',
            ),
            77 => 
            array (
                'id' => 78,
                'title' => 'آشنایی با فونت ها در CSS-فونت فارسی 1',
                'course_section_id' => 213,
                'course_id' => 26,
                'duration' => 512,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 09:42:22',
                'updated_at' => '2024-04-10 09:42:23',
            ),
            78 => 
            array (
                'id' => 79,
                'title' => 'آشنایی با فونت ها در CSS-فونت فارسی 2',
                'course_section_id' => 213,
                'course_id' => 26,
                'duration' => 1213,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 09:46:34',
                'updated_at' => '2024-04-10 09:46:35',
            ),
            79 => 
            array (
                'id' => 80,
                'title' => 'استایل دهی به Link State & Button ',
                'course_section_id' => 213,
                'course_id' => 26,
                'duration' => 771,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 09:48:42',
                'updated_at' => '2024-04-10 09:48:43',
            ),
            80 => 
            array (
                'id' => 81,
            'title' => 'آشنایی با Positioning -قسمت 1 - (Relative-Absolute)',
                'course_section_id' => 213,
                'course_id' => 26,
                'duration' => 546,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 09:50:26',
                'updated_at' => '2024-04-10 10:00:17',
            ),
            81 => 
            array (
                'id' => 82,
            'title' => 'آشنایی آشنایی با Positioning -قسمت 2 - (Fixed)	',
                'course_section_id' => 213,
                'course_id' => 26,
                'duration' => 467,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 09:54:29',
                'updated_at' => '2024-04-10 09:59:06',
            ),
            82 => 
            array (
                'id' => 83,
            'title' => 'آشنایی با Positioning -قسمت 3 (Sticky)	',
                'course_section_id' => 213,
                'course_id' => 26,
                'duration' => 337,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 09:58:36',
                'updated_at' => '2024-04-10 09:58:37',
            ),
            83 => 
            array (
                'id' => 84,
                'title' => 'آشنایی با background-image با مینی پروژه',
                'course_section_id' => 213,
                'course_id' => 26,
                'duration' => 675,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 10:04:03',
                'updated_at' => '2024-04-10 10:04:04',
            ),
            84 => 
            array (
                'id' => 85,
                'title' => 'تفاوت display با visibility',
                'course_section_id' => 213,
                'course_id' => 26,
                'duration' => 328,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 10:05:48',
                'updated_at' => '2024-04-10 10:05:48',
            ),
            85 => 
            array (
                'id' => 86,
                'title' => 'آشنایی با  flex-wrap , flex-direction , flex',
                'course_section_id' => 214,
                'course_id' => 26,
                'duration' => 557,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 10:12:42',
                'updated_at' => '2024-04-10 10:12:43',
            ),
            86 => 
            array (
                'id' => 87,
                'title' => 'بررسی flex-grow, flex-shrink , flex-basis',
                'course_section_id' => 214,
                'course_id' => 26,
                'duration' => 339,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 10:16:27',
                'updated_at' => '2024-04-10 10:23:18',
            ),
            87 => 
            array (
                'id' => 88,
                'title' => 'بررسی justify-content',
                'course_section_id' => 214,
                'course_id' => 26,
                'duration' => 409,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 10:22:56',
                'updated_at' => '2024-04-10 10:22:57',
            ),
            88 => 
            array (
                'id' => 89,
                'title' => 'آشنایی با مفهوم واکنش گرایی قالب وبسایت',
                'course_section_id' => 215,
                'course_id' => 26,
                'duration' => 266,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 10:25:17',
                'updated_at' => '2024-04-10 10:25:17',
            ),
            89 => 
            array (
                'id' => 90,
                'title' => 'آشنایی با Media Query ',
                'course_section_id' => 215,
                'course_id' => 26,
                'duration' => 570,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 10:33:07',
                'updated_at' => '2024-04-10 10:33:08',
            ),
            90 => 
            array (
                'id' => 91,
                'title' => 'واحدهای اندازه گیری -rem , em , px',
                'course_section_id' => 215,
                'course_id' => 26,
                'duration' => 606,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 10:34:55',
                'updated_at' => '2024-04-10 10:34:56',
            ),
            91 => 
            array (
                'id' => 92,
                'title' => 'واحدهای اندازه گیری Vh,Vw',
                'course_section_id' => 215,
                'course_id' => 26,
                'duration' => 764,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 10:37:51',
                'updated_at' => '2024-04-10 10:37:52',
            ),
            92 => 
            array (
                'id' => 93,
                'title' => 'معرفی پروژه',
                'course_section_id' => 216,
                'course_id' => 26,
                'duration' => 236,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 11:19:50',
                'updated_at' => '2024-04-10 11:19:51',
            ),
            93 => 
            array (
                'id' => 94,
                'title' => 'ایجاد ساختار پروژه',
                'course_section_id' => 216,
                'course_id' => 26,
                'duration' => 315,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 11:20:51',
                'updated_at' => '2024-04-10 11:20:52',
            ),
            94 => 
            array (
                'id' => 95,
                'title' => 'طراحی هدر - قسمت 1',
                'course_section_id' => 216,
                'course_id' => 26,
                'duration' => 452,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 11:22:33',
                'updated_at' => '2024-04-10 11:22:34',
            ),
            95 => 
            array (
                'id' => 96,
                'title' => 'طراحی هدر - قسمت 2',
                'course_section_id' => 216,
                'course_id' => 26,
                'duration' => 644,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 11:24:38',
                'updated_at' => '2024-04-10 11:24:39',
            ),
            96 => 
            array (
                'id' => 97,
                'title' => 'طراحی Hero Section قسمت 1',
                'course_section_id' => 216,
                'course_id' => 26,
                'duration' => 698,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 11:31:06',
                'updated_at' => '2024-04-10 15:14:12',
            ),
            97 => 
            array (
                'id' => 98,
                'title' => 'طراحی Hero Section  قسمت 2',
                'course_section_id' => 216,
                'course_id' => 26,
                'duration' => 472,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 15:11:14',
                'updated_at' => '2024-04-10 15:11:15',
            ),
            98 => 
            array (
                'id' => 99,
                'title' => 'استفاده از Fontawesome در پروژه',
                'course_section_id' => 216,
                'course_id' => 26,
                'duration' => 420,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 15:25:08',
                'updated_at' => '2024-04-10 15:25:09',
            ),
            99 => 
            array (
                'id' => 100,
                'title' => 'طراحی سکشن About -قسمت 1',
                'course_section_id' => 216,
                'course_id' => 26,
                'duration' => 687,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 15:27:37',
                'updated_at' => '2024-04-10 15:31:28',
            ),
            100 => 
            array (
                'id' => 101,
                'title' => 'طراحی سکشن About -قسمت 2',
                'course_section_id' => 216,
                'course_id' => 26,
                'duration' => 490,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 15:31:08',
                'updated_at' => '2024-04-10 15:31:09',
            ),
            101 => 
            array (
                'id' => 102,
                'title' => 'طراحی سکشن Cases',
                'course_section_id' => 216,
                'course_id' => 26,
                'duration' => 363,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 15:38:19',
                'updated_at' => '2024-04-10 15:38:20',
            ),
            102 => 
            array (
                'id' => 103,
                'title' => 'طراحی سکشن Blog',
                'course_section_id' => 216,
                'course_id' => 26,
                'duration' => 412,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 15:42:17',
                'updated_at' => '2024-04-10 15:42:18',
            ),
            103 => 
            array (
                'id' => 104,
                'title' => 'طراحی سکشن Team',
                'course_section_id' => 216,
                'course_id' => 26,
                'duration' => 296,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 15:45:08',
                'updated_at' => '2024-04-10 15:45:09',
            ),
            104 => 
            array (
                'id' => 105,
                'title' => 'طراحی سکشن Contact',
                'course_section_id' => 216,
                'course_id' => 26,
                'duration' => 608,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 15:48:52',
                'updated_at' => '2024-04-10 15:48:53',
            ),
            105 => 
            array (
                'id' => 106,
                'title' => 'طراحی Footer	',
                'course_section_id' => 216,
                'course_id' => 26,
                'duration' => 266,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 15:52:40',
                'updated_at' => '2024-04-10 15:52:41',
            ),
            106 => 
            array (
                'id' => 107,
                'title' => 'واکنشگرا کردن قالب  پروژه',
                'course_section_id' => 216,
                'course_id' => 26,
                'duration' => 627,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 15:58:38',
                'updated_at' => '2024-04-10 15:58:40',
            ),
            107 => 
            array (
                'id' => 108,
                'title' => 'سلکتورهای پیشرفته قسمت 1',
                'course_section_id' => 213,
                'course_id' => 26,
                'duration' => 594,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 16:35:45',
                'updated_at' => '2024-04-10 16:35:46',
            ),
            108 => 
            array (
                'id' => 109,
                'title' => 'سلکتورهای پیشرفته قسمت 2',
                'course_section_id' => 213,
                'course_id' => 26,
                'duration' => 401,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 17:22:33',
                'updated_at' => '2024-04-10 17:22:34',
            ),
            109 => 
            array (
                'id' => 110,
                'title' => 'آشنایی با before , after در CSS',
                'course_section_id' => 213,
                'course_id' => 26,
                'duration' => 755,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 19:08:06',
                'updated_at' => '2024-04-10 19:08:07',
            ),
            110 => 
            array (
                'id' => 111,
                'title' => 'ایجاد اولین پروژه و بررسی PHP Tags, Printing & Comments',
                'course_section_id' => 220,
                'course_id' => 27,
                'duration' => 787,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 19:36:57',
                'updated_at' => '2024-04-10 19:37:07',
            ),
            111 => 
            array (
                'id' => 112,
                'title' => 'متغییر ها - Variables',
                'course_section_id' => 220,
                'course_id' => 27,
                'duration' => 616,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 19:38:34',
                'updated_at' => '2024-04-10 19:38:35',
            ),
            112 => 
            array (
                'id' => 113,
                'title' => 'انواع داده - Data Type',
                'course_section_id' => 220,
                'course_id' => 27,
                'duration' => 756,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 19:40:38',
                'updated_at' => '2024-04-10 19:40:39',
            ),
            113 => 
            array (
                'id' => 114,
                'title' => 'آشنایی با مفهوم String Concatenation',
                'course_section_id' => 220,
                'course_id' => 27,
                'duration' => 643,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 19:42:28',
                'updated_at' => '2024-04-10 19:42:29',
            ),
            114 => 
            array (
                'id' => 115,
                'title' => 'بررسی مفهوم Type Casting & Juggling',
                'course_section_id' => 220,
                'course_id' => 27,
                'duration' => 854,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 19:44:53',
                'updated_at' => '2024-04-10 19:44:54',
            ),
            115 => 
            array (
                'id' => 116,
                'title' => 'عملگرها و توابع حسابی- Arithmetic Operators & Functions',
                'course_section_id' => 220,
                'course_id' => 27,
                'duration' => 916,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 19:47:01',
                'updated_at' => '2024-04-10 19:47:02',
            ),
            116 => 
            array (
                'id' => 117,
                'title' => 'توابع مربوط به رشته ها - String Functions',
                'course_section_id' => 220,
                'course_id' => 27,
                'duration' => 585,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 19:48:41',
                'updated_at' => '2024-04-10 19:48:42',
            ),
            117 => 
            array (
                'id' => 118,
                'title' => 'بررسی Dates & Times',
                'course_section_id' => 220,
                'course_id' => 27,
                'duration' => 440,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-10 19:50:29',
                'updated_at' => '2024-04-10 19:50:29',
            ),
            118 => 
            array (
                'id' => 119,
                'title' => 'ایجاد اولین پروژه لاراولی',
                'course_section_id' => 222,
                'course_id' => 28,
                'duration' => 317,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-12 10:01:07',
                'updated_at' => '2024-04-12 10:01:08',
            ),
            119 => 
            array (
                'id' => 120,
                'title' => 'ساختار پوشه ها در لاراول ',
                'course_section_id' => 222,
                'course_id' => 28,
                'duration' => 414,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-12 10:02:56',
                'updated_at' => '2024-04-12 10:02:57',
            ),
            120 => 
            array (
                'id' => 121,
                'title' => ' آشنایی با artisan',
                'course_section_id' => 222,
                'course_id' => 28,
                'duration' => 177,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-12 10:04:28',
                'updated_at' => '2024-04-12 10:04:29',
            ),
            121 => 
            array (
                'id' => 122,
                'title' => 'آشنایی با سیستم Routing ',
                'course_section_id' => 222,
                'course_id' => 28,
                'duration' => 622,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-12 10:06:30',
                'updated_at' => '2024-04-12 10:06:31',
            ),
            122 => 
            array (
                'id' => 123,
            'title' => 'آشنایی با ویو (Blade) و انتقال اطلاعات به ویوها',
                'course_section_id' => 222,
                'course_id' => 28,
                'duration' => 529,
                'free' => 0,
                'deleted_at' => NULL,
                'created_at' => '2024-04-12 10:08:21',
                'updated_at' => '2024-04-12 10:09:06',
            ),
        ));
        
        
    }
}